@url_dev = http://localhost:5000/api/v1

###signup
POST {{url_dev }}/shop/signup
Content-Type: application/json

{
    "name" : "shop",
    "email" : "test@gmail.com",
    "password" : "password123"
}

